### PR TITLE
(PRE-86) Deprecate CLI option --trusted

### PR DESCRIPTION
**Pull request by thallgren**
Since PUP-5061 was fixed, there's no longer a reason to have a --trusted
option. This commit removes the logic that was sensitive to this option
and adds a deprecation warning in case it is used. The warning is
printed conditionally to avoid that it corrupts valid JSON output.

### CODE REVIEW

**Comment by hlindberg** [comment]
Uncertain about this since catalog preview needs to be able to work against 3.8.x. Did PUP-5061 fix that for 3.x ? Or is this standing on another PR that should be reviewed first.

**Comment by hlindberg** [comment]
So PUP-5061 only fixes the problem for Puppet 4.3.2, which means that catalog preview needs to continue restoring the trusted facts the same way as 4.3.2 does it when the the puppet version is older. The --trusted flag should be deprecated.

The help needs to be updated as well.

**Comment by thallgren** [comment]
The change made in PUP-5061 was in puppet/parser/compiler. It was changed because we realized (and agreed) that we must always rely on the trusted data as it is returned from PuppetDB and not resurrect it. This PR performs that same change to catalog_preview. If that's not correct, then I'm again, totally confused.

**Comment by hlindberg** [comment]
I think your assumptions about PUP-5061 are wrong. PuppetDB does not resurrect, puppet does. The behavior from Preview was introduced in Puppet. Later it was also decided that a full resurrection should always be done, not just in the root case. After PUP-5061 puppet will do this. Catalog preview needs to do the same as PUP-5061 for versions of Puppet older than Puppet 4.3.

IIRC correctly, puppet fixes this by sanitation of the node parameters.

To me, it looks like the PR removes all of the behaviour in Catalog Preview, thus making it only work correctly on puppet >= 4.3.

**Comment by thallgren** [comment]
OK, so the correct behavior in catalog-preview would be to disable this conditionally depending on Puppet version?

**Comment by thallgren** [comment]
Another thing to remember is that we never managed to create an acceptance test to prove that PUP-5061 actually made a difference.

**Comment by hlindberg** [comment]
Yes to doing the reincarnation differently depending on puppet version. As first principle requirement: Catalog preview should ensure the behaviour for resurrecting trusted information is the same irrespective of puppet version, and the wanted behavior is that which is in latest puppet 4.x.

**Comment by thallgren** [comment]
And the fact that PUP-5061 just removed dead code?

**Comment by hlindberg** [comment]
The removal of alleged "dead code" made it fall back to what was there before PUP-5061. I don't know when the behaviour before PUP-5061 was changed. At some point in time the behavior was to completely fail when $trusted came from PuppetDB. That was changed (perhaps more than once) into the behaviour that can be observed in puppet 4.x latest. I am sorry if this is vague, but I don't want to trick you by stating something affirmative when neither I nor Kylo knows the exact behavior at different points in the past except that it was "clearly wrong", then "kind of ok, but requirements were wrong", and now "appears to be ok".

Remember that the handling of $trusted is there to make a compilation where facts are retrieved from PuppetDB behave as if the compilation was a regular compilation (where the caching of them solves the problem). The fixes that were made in puppet are for the odd case when puppet db is hit for facts instead of the cache. This just happens to be what catalog preview is doing all the time.

Does that help?

**Comment by thallgren** [comment]
Not really. Now I don't know what version of Puppet that needs `--trusted` and what version that doesn't. Further more, I still have no clue on how to write a test (acceptance or unit) that verifies that the change has an actual impact. To make it even worse, I don't know what the impact is supposed to be in the different versions so I don't know what to test, should I make an attempt to write something.

I would really like someone who knows more about this to create some kind of diagram showing versions and expected behavior.

**Comment by hlindberg** [comment]
You can assume that before Puppet 4.3.0 where PUP-5061 was "fixed" that the behaviour may be different than desired. Therefore catalog preview can, for all versions < 4.3.0 of puppet restore the $trusted as it used to, with the difference that it should not require root to be the effective user in order to restore all of it verbatim. It is not more complicated than that. If an interims version of puppet between 3.x and 4.3.0 managed  to get it right on its own does not matter much, as catalog preview will always do the right thing.

**Comment by thallgren** [comment]
Sure, I can do that. I just dread next steps, when this ends up in QA and hours or days will be spent trying to write acceptance tests for it. Once is enough for that kind of activity.

Why can't the problem be specified? Why is it a problem at all?

**Comment by hlindberg** [comment]
Because it runs on code that is already released. Figuring out which 3.x versions and 4.x versions up to 4.3 that is doing something different with $trusted, if partially correct or not, with different compensation per version does not seem to be well spent time. Better to have catalog preview take over in all of those cases. Which is exactly what catalog preview have been doing all along, only with the requirement that you have to be root for one the pieces of information in $facts. The debate was then if puppet should do the same, and we decided that this was wrong and that it should do a full reincarnation. The PUP-5061 was the last ticket on that work. At that point we have defined behavior.

The original problem is that PuppetDB decided to store $trusted the same way as facts. That is wrong. But that is what it is doing. And it is doing that in versions that catalog preview has to run against. Actually making the change in PuppetDB becomes a big thing as all historical data needs to be transformed, it affects integration, the UI etc. In short, it is a a big thing to change. Instead, puppet (and catalog preview) needs to handle this when information comes back directly from PuppetDB (which it always does in catalog preview).

Not restoring trusted facts is a problem because compilation may depend on them, We do not want catalog preview compilations to be different from the original compilations. And hence the information needs to be restored as if the node were making the request to compile.

**Comment by thallgren** [comment]
Perhaps I was unclear. I have no problem that catalog-preview makes an effort to rectify mistakes made in the past one way or another. What bothers me is that we haven't been able to come up with a use-case where we can prove that this actually is what's happening. This tells me that we think that something is wrong and we think that we might need to fix it, but we don't know any of it for certain. Until we do, it feels rather pointless to fix problems that we cannot pinpoint or provide a test-case for.

**Comment by hlindberg** [comment]
Prove that "what happens"? What we had problem proving was that the dead code that was removed in PUP-5061 made a difference; hence it *may* have worked in a version between failing for sure, and not failing. Probably because of a bug in the earlier implementation - it was intended to do something differently, but ended up unintentionally resurrecting the $trusted verbatim. If you step back far enough you hit the version where it will surely not work because $trusted coming back from PuppetDB is not handled at all.

The `trusted['authenticated']` is supposed to be the value that was originally stored in PuppetDB when the request came from the node. That is what should change in Catalog Preview for puppet versions < puppet 4.3.0. That is the correct behavior that Puppet >= 4.3.0) has (and which catalog preview then does not have to compensate for as the node implementation then, on its own, can resurrect the $trusted information correctly in the form it is delivered from PuppetDB).

**Comment by thallgren** [comment]
This is getting nowhere as we talk past each other. You write "we had a problem". I don't doubt that. I just want that problem described. For three reasons really:

1. To be able to test that the --trusted in it's current form has the desired impact.
2. To be able to test that we get the desired output without --trusted and versions >= 4.3.0
3. To understand why removing the use of --trusted in the current beaker tests (runs against Puppet 3.8.1) doesn't do one bit of a difference.

**Comment by hlindberg** [comment]
The use case is: full roundtrip to puppet-db with facts from a node, then use those facts in catalog preview. IIRC, we do not have such acceptance tests. If wanting unit tests the puppet db way of delivering the data (including $trusted) would need to be mocked.

Then, to actually see the bad behavior, the catalog content needs to depend on the $trusted data, i.e. `$trusted[authenticated]` (e.g. including something 'secret' when authenticated is 'remote').

If this happens to work on 3.8.1 as non root user (work == authenticated[remote] is restored) then that is pure divine interception as that would have been a bug before we decided to restore $trusted verbatim.

Does that help? If not, we need to talk to speed up the resolution of this :-)

**Comment by thallgren** [comment]
It helps. And I think we should defer this issue until we have an acceptance test that can assert whether or not the current solution works (it's completely untested and AFAIK we have had no feedback to confirm that it has an impact), what version it works against, and if removing it will make a difference.

**Comment by hlindberg** [comment]
The mere fact that preview changes `authenticated` if non root means it is doing it wrong. That does not require an acceptance test to figure out. If that is the only change we make it will probably work against all puppet versions (even if it is potentially doing the job twice on newer puppet (or does it for node so it doesn't have to)).

**Comment by hlindberg** [comment]
i.e. this PR should: deprecate the use of --trusted, and then do what it used to do when --trusted was set and user was root.

**Comment by thallgren** [comment]
I see now that the code in question is a copy of the method `sanitize_node` introduced by PUP-5441. I'll copy that over it's current shape (this is the method that was modified by PUP-5061).

**Comment by hlindberg** [comment]
And the circle is complete - the sanitize_node is a copy from the implementation in catalog_preview :-)

**Comment by thallgren** [comment]
Pushed a new commit that is rebased on master and uses a copy of the sanitize_node method.

**Comment by hlindberg** [comment]
That looks fine. Think the tests should not be all deleted.

* test that it issues a deprecation warning if --trusted is used
* test that all of the trusted information is made available (there were different tests for root vs. noon root, flag on/off etc. That should be cleaned up.

**Pull request merged**
